### ISSUE TITLE
TypeError: Cannot read properties of null (reading '$') on email input

### ISSUE THREAD

**Issue by nailserverzone** [theoomoregbee/US-visa-appointment-notifier#16] opened 2023-02-22 22:15 UTC
This error appear and corresponds to the line where it's written const email = await form.$('input[name="user[email]"]');

**Comment by theoomoregbee** [comment] 2023-02-23 13:16
This was already resolved, you need to download the latest copy of the code. 

Duplicate of https://github.com/theoomoregbee/US-visa-appointment-notifier/issues/12

**Closed as completed by theoomoregbee** 2023-02-23 13:16 UTC
